<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<RootNamespace>Video_Printer</RootNamespace>
		<StartupObject>Video_Printer.Program</StartupObject>
		<Platforms>AnyCPU;x64;x86;ARM64</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Drawing.Common" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Image Printer\Image Printer.csproj" />
		<ProjectReference Include="..\Image Printer.Video\Image Printer.Video.csproj" />
	</ItemGroup>
</Project>
