<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <RootNamespace>Image_Printer_CLI</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <StartupObject>Image_Printer_CLI.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Image Printer\Image Printer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="9.0.3" />
  </ItemGroup>

</Project>
